first commit for jenkins 2

diff --git a/JenkinsFile b/JenkinsFile
--- a/JenkinsFile
+++ b/JenkinsFile
@@ -10,7 +10,26 @@ pipeline {
     }
 
     stages {
-
+         stage('Install Docker') {
+            steps {
+                script {
+                    echo 'Installing Docker...'
+                    // בדוק אם דוקר מותקן, ואם לא, התקן אותו
+                    sh '''
+                    if ! command -v docker &> /dev/null
+                    then
+                        echo "Docker could not be found, installing..."
+                        sudo apt-get update -y
+                        sudo apt-get install -y docker.io
+                        sudo systemctl enable docker
+                        sudo systemctl start docker
+                    else
+                        echo "Docker is already installed"
+                    fi
+                    '''
+                }
+            }
+        }
         stage('Clone Repository') {
             steps {
                 // I switch to docker branch to get the Dockerfile
