jenpipe 1

diff --git a/JenkinsFile b/JenkinsFile
--- a/JenkinsFile
+++ b/JenkinsFile
@@ -10,25 +10,25 @@ pipeline {
     }
 
     stages {
-         stage('Install Docker') {
-            steps {
-                script {
-                    echo 'Installing Docker...'
-                    sh '''
-                    if ! command -v docker &> /dev/null
-                    then
-                        echo "Docker could not be found, installing..."
-                        apt-get update -y
-                        apt-get install -y docker.io
-                        systemctl enable docker
-                        systemctl start docker
-                    else
-                        echo "Docker is already installed"
-                    fi
-                    '''
-                }
-            }
-        }
+        //  stage('Install Docker') {
+        //     steps {
+        //         script {
+        //             echo 'Installing Docker...'
+        //             sh '''
+        //             if ! command -v docker &> /dev/null
+        //             then
+        //                 echo "Docker could not be found, installing..."
+        //                 apt-get update -y
+        //                 apt-get install -y docker.io
+        //                 systemctl enable docker
+        //                 systemctl start docker
+        //             else
+        //                 echo "Docker is already installed"
+        //             fi
+        //             '''
+        //         }
+        //     }
+        // }
         stage('Clone Repository') {
             steps {
                 // I switch to docker branch to get the Dockerfile
